services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   
    # environment:
    #   - REACT_APP_API_URL=http://localhost:8001

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/user:/app/user
    ports:
      - "8001:8001"   
    
